### ISSUE TITLE
Release tracking issue

### ISSUE THREAD

**Issue by talex5** [ocaml-multicore/ocaml-uring#23]
Things to sort out before release:

- [x] There are a load of `/* TODO sort out cast */` comments in the cstubs (originally added by @avsm) - not sure what needs to be done here.
- [x] Check we never GC things that are still in use (see e.g. #10).
- [x] Sort out iovecs. @avsm doesn't like the current API. Check GC behaviour, alignment TODO.
- [x] `TODO: replace with {!Region.t} instead.` in API. Should be easy enough.

**Comment by avsm** [comment]
I think the casting issue is making sure that the user-supplied data pointer is munged appropriately into being an integer instead of a pointer.

Could release iovec library separately. The main problem with current interface is the `adjust` unsafe call to modify the size. But also, we need to be able to heap allocate the iovec for uring, which is not usually the case.  It would be worth building a simple slab allocator into an `iovec` library for that purpose.

**Comment by avsm** [comment]
And this needs to be deleted as well :-) https://github.com/ocaml-multicore/ocaml-uring/blob/main/lib/uring/uring.mli#L18

**Comment by talex5** [comment]
The remaining TODOs don't look very serious:
```
lib/uring/dune:      ;; TODO discover.ml for liburing cflags
lib/uring/region.ml:(* TODO turn into a variable length slab allocator *)
lib/uring/uring.ml:  (* TODO posix memalign this to page *)
lib/uring/uring_stubs.c:// TODO: this belongs in Optint
tests/cptest.ml:  (* TODO check they are the same file *)
tests/urcat.ml:(* TODO make this work with ST_ISBLK *)
tests/urcp_fixed_lib.ml:(* TODO make this work with ST_ISBLK *)
tests/urcp_fixed_lib.ml:(* TODO compile time check *)
tests/urcp_fixed_lib.ml:   Gc.compact () (* TODO to aid debugging with valgrind, remove soon *)
tests/urcp_lib.ml:(* TODO make this work with ST_ISBLK *)
tests/urcp_lib.ml:(* TODO compile time check *)
tests/urcp_lib.ml:   Gc.compact () (* TODO to aid debugging with valgrind, remove soon *)
vendor/dune:      ;; TODO discover.ml for liburing cflags
```
Any objections to releasing with the current API?

**Comment by avsm** [comment]
I think the configure discover.ml may be useful to grab the ocaml C compiler flags as otherwise it might not work on x32 or arm ("-g -fomit-frame-pointer -fPIC"). Or can just release as arch=x86_64 os=linux to start with

**Comment by talex5** [comment]
Getting the compiler flags turned out to be easier than expected!

**Comment by avsm** [comment]
Looks good. Just the README file needs a bit of spring cleaning for a first release.

**Comment by avsm** [comment]
And you need to add yourself to the authors list!
